### ISSUE TITLE
Add option for default email address from config

### ISSUE THREAD

**Issue by Brixy** [martignoni/hugo-cloak-email#10]
I use your brilliant shortcode heavily in many projects. Now I had to change all email addresses in one of them. So this is what I am using now:

In `cloakemail.html`:

```
{{- $address := .Get "address" | default .Site.Params.themeSettings.cloakemail -}}
```

config.yaml:

```
params:
  themeSettings:
    cloakemail: "mail@test.com"
    …
```

Does this make sense to you? Yet, other user might prefer a default phone number etc. So an address in this format `address="emaildefault"` might make more sense.

Thank you!
